### ISSUE TITLE
Memory issue on M1 Chip

### ISSUE THREAD

**Issue by AngelOnFira** [nannou-org/nannou#772] opened 2021-07-17 00:14 UTC
I just started following the Nannou [getting started guide](https://guide.nannou.cc/getting_started/create_a_project.html). On step 4 of the guide, after compiling the code, it would lead to an OOM if I left it open for more than several seconds. Specifically, this is the code:
```rust
use nannou::prelude::*;

fn main() {
    nannou::app(model)
        .update(update)
        .simple_window(view)
        .run();
}

struct Model {}

fn model(_app: &App) -> Model {
    Model {}
}

fn update(_app: &App, _model: &mut Model, _update: Update) {
}

fn view(_app: &App, _model: &Model, frame: Frame){
    frame.clear(PURPLE);
}
```
I'd be happy to get any more diagnostics that would be helpful. I know that this could very well be external, say issues with wgpu on the M1 or something, but I just tried doing some work with Nannou first, so this is where I saw the error.

**Comment by mitchmindtree** [comment] 2021-07-17 18:29
Thanks for the issue!

Hmm I wonder if you're running into this? https://github.com/gfx-rs/wgpu/issues/1501

If you think it might be, you can try adding this patch to your `Cargo.toml` to replace the wgpu version with the previous version (which doesn't leak):

```toml
[patch.crates-io.wgpu]
git = "https://github.com/mitchmindtree/wgpu-rs"
branch = "0.8-as-0.9"
```

Could you try running your program with `RUST_BACKTRACE=full`? This should provide a stack trace upon crash which might give us an idea of what is causing the OOM error.

**Comment by aekasitt** [comment] 2021-11-02 09:42
Ran into similar problem with the original poster and the patch for `wgpu` seemingly solved my problem. Thanks!

**Comment by mitchmindtree** [comment] 2021-12-15 08:47
Thanks @aekasitt, closing for now as this appears to be solved, but feel free to re-open if the issue is still there.

**Closed by mitchmindtree** 2021-12-15 08:47 UTC
